-- Generated by scripts/build-supabase-sql-bundles.mjs.
-- Review before running in Supabase SQL Editor.
-- Bundle: live_cleanup_apply.sql
-- Purpose: Write bundle for the current live project after reviewing the preflight output.


-- =====================================================================
-- supabase/migrations/202606130001_harden_class_students_tenant_scope.sql
-- =====================================================================

-- Harden the current Next.js grade UI enrollment table.
--
-- `class_students` belongs to the app-facing grade track
-- (`class_students` / `tasks` / `task_records`). It originally relied on
-- `classes.tenant_id` indirectly. This migration adds direct tenant scope so
-- RLS can use the same policy shape as the other business tables.

alter table public.class_students
  add column if not exists tenant_id uuid;

update public.class_students cs
set tenant_id = c.tenant_id
from public.classes c
where cs.class_id = c.id
  and cs.tenant_id is distinct from c.tenant_id;

create or replace function public.set_class_students_tenant_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  class_tenant_id uuid;
  student_tenant_id uuid;
begin
  select c.tenant_id
    into class_tenant_id
    from public.classes c
    where c.id = new.class_id;

  if class_tenant_id is null then
    raise exception 'class_students.class_id % does not exist', new.class_id;
  end if;

  select s.tenant_id
    into student_tenant_id
    from public.students s
    where s.id = new.student_id;

  if student_tenant_id is null then
    raise exception 'class_students.student_id % does not exist', new.student_id;
  end if;

  if student_tenant_id <> class_tenant_id then
    raise exception 'class_students class/student tenant mismatch';
  end if;

  if new.tenant_id is null then
    new.tenant_id := class_tenant_id;
  elsif new.tenant_id <> class_tenant_id then
    raise exception 'class_students.tenant_id must match classes.tenant_id';
  end if;

  return new;
end;
$$;

drop trigger if exists set_class_students_tenant_id on public.class_students;
create trigger set_class_students_tenant_id
  before insert or update of class_id, student_id, tenant_id
  on public.class_students
  for each row
  execute function public.set_class_students_tenant_id();

do $$
begin
  if exists (
    select 1
    from public.class_students cs
    join public.classes c on c.id = cs.class_id
    join public.students s on s.id = cs.student_id
    where cs.tenant_id is distinct from c.tenant_id
       or s.tenant_id is distinct from c.tenant_id
  ) then
    raise exception 'class_students contains tenant mismatches';
  end if;
end;
$$;

alter table public.class_students
  alter column tenant_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.class_students'::regclass
      and conname = 'class_students_tenant_id_fkey'
  ) then
    alter table public.class_students
      add constraint class_students_tenant_id_fkey
      foreign key (tenant_id)
      references public.tenants(id)
      on delete cascade;
  end if;
end;
$$;

create index if not exists idx_class_students_tenant_class_status
  on public.class_students (tenant_id, class_id, status);

alter table public.class_students enable row level security;
grant select, insert, update, delete on public.class_students to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'class_students'
      and policyname = 'tenant members can manage'
  ) then
    execute '
      create policy "tenant members can manage"
        on public.class_students
        for all
        to authenticated
        using (
          tenant_id in (
            select p.tenant_id
            from public.profiles p
            where p.id = auth.uid()
          )
        )
        with check (
          tenant_id in (
            select p.tenant_id
            from public.profiles p
            where p.id = auth.uid()
          )
        )
    ';
  end if;
end;
$$;


-- =====================================================================
-- supabase/migrations/202606130002_backfill_grade_ui_from_legacy_track.sql
-- =====================================================================

-- Backfill the current Next.js grade UI track from the legacy import track.
--
-- This migration intentionally copies only structural rows:
-- - class_enrollments -> class_students
-- - class_tasks -> tasks
--
-- It does not create task_records. The current app already has an explicit
-- dispatch flow that creates per-student task_records after teachers review a
-- class's roster and task list.

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'class_students'
      and column_name = 'tenant_id'
  ) then
    raise exception 'Run 202606130001_harden_class_students_tenant_scope.sql before this backfill.';
  end if;
end;
$$;

do $$
begin
  if exists (
    with task_type_map as (
      select *
      from (
        values
          (U&'\51FA\5E2D', 'attendance'),
          (U&'\4F5C\696D', 'homework'),
          (U&'\7DF4\7FD2', 'practice'),
          (U&'\8003\8A66', 'quiz'),
          (U&'\8A55\8AD6', 'comment')
      ) as mapped(legacy_task_type, app_task_type)
    )
    select 1
    from public.class_tasks ct
    left join public.tasks existing_same_class
      on existing_same_class.class_id = ct.class_id
     and existing_same_class.task_code = ct.legacy_task_id
    left join task_type_map tm on tm.legacy_task_type = ct.task_type
    where ct.status = 'active'
      and ct.class_id is not null
      and ct.legacy_task_id is not null
      and existing_same_class.id is null
      and tm.app_task_type is null
  ) then
    raise exception 'Some legacy class_tasks have unmapped task_type values.';
  end if;

  if exists (
    select 1
    from public.class_tasks ct
    join public.tasks existing_same_tenant
      on existing_same_tenant.tenant_id = ct.tenant_id
     and existing_same_tenant.task_code = ct.legacy_task_id
     and existing_same_tenant.class_id is distinct from ct.class_id
    left join public.tasks existing_same_class
      on existing_same_class.class_id = ct.class_id
     and existing_same_class.task_code = ct.legacy_task_id
    where ct.status = 'active'
      and ct.class_id is not null
      and ct.legacy_task_id is not null
      and existing_same_class.id is null
  ) then
    raise exception 'Some legacy class_tasks would collide with existing tasks.task_code values.';
  end if;
end;
$$;

insert into public.class_students (
  tenant_id,
  class_id,
  student_id,
  slot_order,
  status
)
select
  ce.tenant_id,
  ce.class_id,
  ce.student_id,
  coalesce(ce.slot_index, 0),
  'active'
from public.class_enrollments ce
where ce.status = 'active'
  and ce.class_id is not null
  and ce.student_id is not null
  and not exists (
    select 1
    from public.class_students cs
    where cs.class_id = ce.class_id
      and cs.student_id = ce.student_id
  )
on conflict (class_id, student_id) do nothing;

with task_type_map as (
  select *
  from (
    values
      (U&'\51FA\5E2D', 'attendance'),
      (U&'\4F5C\696D', 'homework'),
      (U&'\7DF4\7FD2', 'practice'),
      (U&'\8003\8A66', 'quiz'),
      (U&'\8A55\8AD6', 'comment')
  ) as mapped(legacy_task_type, app_task_type)
)
insert into public.tasks (
  tenant_id,
  class_id,
  task_code,
  week,
  lesson_number,
  task_type,
  task_name,
  threshold,
  display_order
)
select
  ct.tenant_id,
  ct.class_id,
  ct.legacy_task_id,
  coalesce(nullif(ct.week, ''), 'W1'),
  coalesce(nullif(ct.lesson, ''), 'L1'),
  tm.app_task_type,
  nullif(ct.task_name, ''),
  case
    when regexp_replace(coalesce(ct.threshold, ''), '[^0-9.]', '', 'g') ~ '^[0-9]+(\.[0-9]+)?$'
      then regexp_replace(coalesce(ct.threshold, ''), '[^0-9.]', '', 'g')::numeric
    else null
  end,
  coalesce(ct.source_row, 0)
from public.class_tasks ct
join task_type_map tm on tm.legacy_task_type = ct.task_type
where ct.status = 'active'
  and ct.class_id is not null
  and ct.legacy_task_id is not null
  and not exists (
    select 1
    from public.tasks existing_same_class
    where existing_same_class.class_id = ct.class_id
      and existing_same_class.task_code = ct.legacy_task_id
  )
  and not exists (
    select 1
    from public.tasks existing_same_tenant
    where existing_same_tenant.tenant_id = ct.tenant_id
      and existing_same_tenant.task_code = ct.legacy_task_id
      and existing_same_tenant.class_id is distinct from ct.class_id
  )
on conflict (tenant_id, task_code) do nothing;

